title: Rahul Hans
#logo: /assets/img/headshot_circle.png
logo: /assets/img/NAme1.png
description: Dr. Rahul Hans
#show_downloads: true
# if you don't have any of social below, comment the line
#<a href="https://in.linkedin.com/">View My LinkedIn Profile</a>

#remote_theme: tedivm/jekyll-theme-portfolio

theme: jekyll-theme-minimal
#remote_theme: pages-themes/time-machine@v0.2.0
#remote_theme: pages-themes/architect@v0.2.0

