title: Rahul Hans
#logo: /assets/img/headshot_circle.png
logo: /assets/img/NAme1.png
description: Dr. Rahul Hans <br> Connect with me: <br> LinkdIn
#show_downloads: true
theme: jekyll-theme-minimal
#remote_theme: pages-themes/time-machine@v0.2.0
#remote_theme: pages-themes/architect@v0.2.0

